# This is a basic workflow that is manually triggered

name: Generate Release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      ver:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Version'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: false

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.Js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          scope: jasonlwalker
          user: jasonlwalker
          access: public 
          registry-url: 'https://registry.npmjs.org'
         
      - name: Configure Git user
        run: |
             git config --global user.email "jason@draxjinn.com"
             git config --global user.name "Jason Walker"
        
      - name: Install np
        run: npm install --global np
      
      - name: Create Release
        run: np patch
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
      - uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'
          repository-type: "git"
          repository-url: "https://github.com/JasonLWalker/Jlw.Package.Releases.git"
          repository-directory: "jasonlwalker/jlwutility"
          # Defaults to the user or organization that owns the workflow file
          scope: ${{ secrets.GPR_USER }}
      # Publish to GitHub Packages
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GPR_TOKEN }}
        
        
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: Release ${{ github.ref }}
#          body: |
#            Changes in this Release
#            - First Change
#            - Second Change
#          draft: false
#          prerelease: false
