# This is a basic workflow that is manually triggered

name: Publish Release Patch

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    #    required: false

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.Js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          scope: ${{ secrets.NPM_USER }}
          user: ${{ secrets.NPM_USER }}
          access: public 
          registry-url: 'https://registry.npmjs.org'
         
      - run: npm install --global uglify-js
         
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git user
        run: |
             git config --global user.email '${{ secrets.GIT_USER_EMAIL }}'
             git config --global user.name '${{ secrets.GIT_USER_NAME }}'
             git config pull.rebase false
        
      - name: Configure before publish
        run: |
             npm update
             npm run build
             git add package.json
             git add libJlwUtility.min.js
             git commit -a -m "bump version and minify library" --allow-empty
             git push -f origin ${{ github.ref_name }}
        env:
             NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
             
      - name: Publish to npm
        run: npm publish --access public
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Configure Node.Js
        uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '${{ secrets.GPR_USER }}'
      
      - name: Publish to GPR
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GPR_TOKEN }}        

